import pydantic as _pydantic
from typing import Optional
from datetime import date, datetime
from backend.enums import TransactionType, BudgetPeriod, RecurrenceFrequency, ExportFormat

# ============================================================================
# User Schemas
# ============================================================================

# Contains fields that are common to creating, reading, and updating.
class UserBase(_pydantic.BaseModel):
    email: _pydantic.EmailStr

# Used when a user registers. We need the plain password here.
class UserCreate(UserBase):
    password: str 
    class Config:
        from_attributes = True

class UserLogin(UserBase):
    password: str

# Used for profile updates. All fields are optional.
class UserUpdate(_pydantic.BaseModel):
    email: Optional[_pydantic.EmailStr] = None
    password: Optional[str] = None

# Used when returning data to the client.
# - Includes the ID and Date Created (generated by DB).
class UserResponse(UserBase):
    id: int
    date_created: datetime

    # This configuration tells Pydantic to treat the SQLAlchemy object
    # as a dictionary so it can populate these fields.
    model_config = _pydantic.ConfigDict(from_attributes=True)

# ============================================================================
# Category Schemas
# ============================================================================

class CategoryBase(_pydantic.BaseModel):
    name: str
    type: TransactionType

class CategoryCreate(CategoryBase):
    color: Optional[str] = None
    icon: Optional[str] = None


class CategoryUpdate(_pydantic.BaseModel):
    name: Optional[str] = None
    type: Optional[TransactionType] = None
    color: Optional[str] = None
    icon: Optional[str] = None

class CategoryResponse(CategoryBase):
    id: int
    color: Optional[str]
    icon: Optional[str]
    is_default: bool
    created_at: datetime

    model_config = _pydantic.ConfigDict(from_attributes=True)

# ============================================================================
# Transaction Schemas
# ============================================================================

class TransactionBase(_pydantic.BaseModel):
    amount: float
    type: TransactionType

class TransactionCreate(TransactionBase):
    category_id: int
    description: Optional[str] = None
    transaction_date: Optional[date] = None
    receipt_url: Optional[str] = None

class TransactionUpdate(_pydantic.BaseModel):
    amount: Optional[float] = None
    type: Optional[TransactionType] = None
    category_id: Optional[int] = None
    description: Optional[str] = None
    transaction_date: Optional[date] = None
    receipt_url: Optional[str] = None

class TransactionResponse(TransactionBase):
    id: int
    category_id: int
    description: Optional[str] = None
    date: date
    receipt_url: Optional[str] = None

    model_config = _pydantic.ConfigDict(from_attributes=True)


# ============================================================================
# Budget Schemas
# ============================================================================

class BudgetBase(_pydantic.BaseModel):
    amount: float
    period: BudgetPeriod

class BudgetCreate(BudgetBase):
    category_id: int
    start_date: date

class BudgetUpdate(_pydantic.BaseModel):
    amount: Optional[float] = None
    period: Optional[BudgetPeriod] = None
    is_active: Optional[bool] = None

class BudgetResponse(BudgetBase):
    id: int
    category_id: int
    start_date: date
    is_active: bool

    model_config = _pydantic.ConfigDict(from_attributes=True)

# ============================================================================
# Recurring Transaction Schemas
# ============================================================================

class RecurringTransactionBase(_pydantic.BaseModel):
    amount: float
    type: TransactionType
    frequency: RecurrenceFrequency
    start_date: date
    category_id: int

class RecurringTransactionCreate(RecurringTransactionBase):
    description: Optional[str] = None
    end_date: Optional[date] = None

class RecurringTransactionUpdate(_pydantic.BaseModel):
    amount: Optional[float] = None
    type: Optional[str] = None
    frequency: Optional[RecurrenceFrequency] = None
    start_date: Optional[date] = None
    category_id: Optional[int] = None
    description: Optional[str] = None
    end_date: Optional[date] = None
    is_active: Optional[bool] = None

class RecurringTransactionResponse(RecurringTransactionBase):
    description: Optional[str] = None
    end_date: Optional[date] = None
    is_active: bool

    model_config = _pydantic.ConfigDict(from_attributes=True)
